package siri_sm_demo;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import static siri_sm_demo.Siri_sm_wsdl.Send_siri_sm_req;

public class Siri_sm_demo extends javax.swing.JFrame {

    public Siri_sm_demo() {
        initComponents();
        Clear_labels();
    }

    private void Clear_labels() {
        Status.setText("");
        Agency1.setText("");
        Dest1.setText("");
        Line1.setText("");
        Time1.setText("");
        
        Agency2.setText("");
        Dest2.setText("");
        Line2.setText("");
        Time2.setText("");
        
        Agency3.setText("");
        Dest3.setText("");
        Line3.setText("");
        Time3.setText("");

        Agency4.setText("");
        Dest4.setText("");
        Line4.setText("");
        Time4.setText("");

        Agency5.setText("");
        Dest5.setText("");
        Line5.setText("");
        Time5.setText("");

        Agency6.setText("");
        Dest6.setText("");
        Line6.setText("");
        Time6.setText("");

        Agency7.setText("");
        Dest7.setText("");
        Line7.setText("");
        Time7.setText("");

        Agency8.setText("");
        Dest8.setText("");
        Line8.setText("");
        Time8.setText("");

        Agency9.setText("");
        Dest9.setText("");
        Line9.setText("");
        Time9.setText("");

        Agency10.setText("");
        Dest10.setText("");
        Line10.setText("");
        Time10.setText("");
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select_station = new javax.swing.JLabel();
        req_station = new javax.swing.JTextField();
        done = new javax.swing.JButton();
        Time1 = new javax.swing.JFormattedTextField();
        Dest1 = new javax.swing.JFormattedTextField();
        Line1 = new javax.swing.JFormattedTextField();
        Time2 = new javax.swing.JFormattedTextField();
        Dest2 = new javax.swing.JFormattedTextField();
        Line2 = new javax.swing.JFormattedTextField();
        Agency1 = new javax.swing.JFormattedTextField();
        Agency2 = new javax.swing.JFormattedTextField();
        Line3 = new javax.swing.JFormattedTextField();
        Agency3 = new javax.swing.JFormattedTextField();
        Time3 = new javax.swing.JFormattedTextField();
        Dest3 = new javax.swing.JFormattedTextField();
        select_station1 = new javax.swing.JLabel();
        select_station2 = new javax.swing.JLabel();
        select_station3 = new javax.swing.JLabel();
        select_station4 = new javax.swing.JLabel();
        Line4 = new javax.swing.JFormattedTextField();
        Agency4 = new javax.swing.JFormattedTextField();
        Time4 = new javax.swing.JFormattedTextField();
        Dest4 = new javax.swing.JFormattedTextField();
        Agency5 = new javax.swing.JFormattedTextField();
        Dest5 = new javax.swing.JFormattedTextField();
        Line5 = new javax.swing.JFormattedTextField();
        Time5 = new javax.swing.JFormattedTextField();
        Line6 = new javax.swing.JFormattedTextField();
        Agency6 = new javax.swing.JFormattedTextField();
        Dest6 = new javax.swing.JFormattedTextField();
        Time6 = new javax.swing.JFormattedTextField();
        Dest7 = new javax.swing.JFormattedTextField();
        Agency7 = new javax.swing.JFormattedTextField();
        Line7 = new javax.swing.JFormattedTextField();
        Time7 = new javax.swing.JFormattedTextField();
        Line8 = new javax.swing.JFormattedTextField();
        Dest8 = new javax.swing.JFormattedTextField();
        Agency8 = new javax.swing.JFormattedTextField();
        Time8 = new javax.swing.JFormattedTextField();
        Agency9 = new javax.swing.JFormattedTextField();
        Time9 = new javax.swing.JFormattedTextField();
        Line9 = new javax.swing.JFormattedTextField();
        Dest9 = new javax.swing.JFormattedTextField();
        Time10 = new javax.swing.JFormattedTextField();
        Line10 = new javax.swing.JFormattedTextField();
        Dest10 = new javax.swing.JFormattedTextField();
        Agency10 = new javax.swing.JFormattedTextField();
        Status = new javax.swing.JFormattedTextField();
        StatusH = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        select_station.setText("Select station No.");

        req_station.setText("32902");

        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });

        Time1.setBackground(new java.awt.Color(153, 255, 255));
        Time1.setText("Time1");

        Dest1.setBackground(new java.awt.Color(153, 255, 255));
        Dest1.setText("Dest1");

        Line1.setBackground(new java.awt.Color(153, 255, 255));
        Line1.setText("Line1");

        Time2.setBackground(new java.awt.Color(153, 255, 255));
        Time2.setText("Time2");

        Dest2.setBackground(new java.awt.Color(153, 255, 255));
        Dest2.setText("Dest2");

        Line2.setBackground(new java.awt.Color(153, 255, 255));
        Line2.setText("Line2");

        Agency1.setBackground(new java.awt.Color(153, 255, 255));
        Agency1.setText("Agency1");

        Agency2.setBackground(new java.awt.Color(153, 255, 255));
        Agency2.setText("Agency2");

        Line3.setBackground(new java.awt.Color(153, 255, 255));
        Line3.setText("Line3");

        Agency3.setBackground(new java.awt.Color(153, 255, 255));
        Agency3.setText("Agency3");

        Time3.setBackground(new java.awt.Color(153, 255, 255));
        Time3.setText("Time3");

        Dest3.setBackground(new java.awt.Color(153, 255, 255));
        Dest3.setText("Dest3");

        select_station1.setText("זמן");

        select_station2.setText("יעד");

        select_station3.setText("קו");

        select_station4.setText("מפעיל");

        Line4.setBackground(new java.awt.Color(153, 255, 255));
        Line4.setText("Line4");

        Agency4.setBackground(new java.awt.Color(153, 255, 255));
        Agency4.setText("Agency4");

        Time4.setBackground(new java.awt.Color(153, 255, 255));
        Time4.setText("Time4");

        Dest4.setBackground(new java.awt.Color(153, 255, 255));
        Dest4.setText("Dest4");

        Agency5.setBackground(new java.awt.Color(153, 255, 255));
        Agency5.setText("Agency5");

        Dest5.setBackground(new java.awt.Color(153, 255, 255));
        Dest5.setText("Dest5");

        Line5.setBackground(new java.awt.Color(153, 255, 255));
        Line5.setText("Line5");

        Time5.setBackground(new java.awt.Color(153, 255, 255));
        Time5.setText("Time5");

        Line6.setBackground(new java.awt.Color(153, 255, 255));
        Line6.setText("Line6");

        Agency6.setBackground(new java.awt.Color(153, 255, 255));
        Agency6.setText("Agency6");

        Dest6.setBackground(new java.awt.Color(153, 255, 255));
        Dest6.setText("Dest6");

        Time6.setBackground(new java.awt.Color(153, 255, 255));
        Time6.setText("Time6");

        Dest7.setBackground(new java.awt.Color(153, 255, 255));
        Dest7.setText("Dest7");

        Agency7.setBackground(new java.awt.Color(153, 255, 255));
        Agency7.setText("Agency7");

        Line7.setBackground(new java.awt.Color(153, 255, 255));
        Line7.setText("Line7");

        Time7.setBackground(new java.awt.Color(153, 255, 255));
        Time7.setText("Time7");

        Line8.setBackground(new java.awt.Color(153, 255, 255));
        Line8.setText("Line8");

        Dest8.setBackground(new java.awt.Color(153, 255, 255));
        Dest8.setText("Dest8");

        Agency8.setBackground(new java.awt.Color(153, 255, 255));
        Agency8.setText("Agency8");

        Time8.setBackground(new java.awt.Color(153, 255, 255));
        Time8.setText("Time8");

        Agency9.setBackground(new java.awt.Color(153, 255, 255));
        Agency9.setText("Agency9");

        Time9.setBackground(new java.awt.Color(153, 255, 255));
        Time9.setText("Time9");

        Line9.setBackground(new java.awt.Color(153, 255, 255));
        Line9.setText("Line9");

        Dest9.setBackground(new java.awt.Color(153, 255, 255));
        Dest9.setText("Dest9");

        Time10.setBackground(new java.awt.Color(153, 255, 255));
        Time10.setText("Time10");

        Line10.setBackground(new java.awt.Color(153, 255, 255));
        Line10.setText("Line10");

        Dest10.setBackground(new java.awt.Color(153, 255, 255));
        Dest10.setText("Dest10");

        Agency10.setBackground(new java.awt.Color(153, 255, 255));
        Agency10.setText("Agency10");

        Status.setBackground(new java.awt.Color(153, 255, 255));
        Status.setText("Status");

        StatusH.setText("Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest4, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest5, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest6, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest7, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest8, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest9, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Time10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Dest10, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Line10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Agency10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StatusH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(select_station)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(req_station, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(select_station1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(select_station2)
                                .addGap(179, 179, 179)
                                .addComponent(select_station3)
                                .addGap(45, 45, 45)
                                .addComponent(select_station4))
                            .addComponent(done))))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_station)
                    .addComponent(req_station, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(done))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StatusH))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_station1)
                    .addComponent(select_station2)
                    .addComponent(select_station3)
                    .addComponent(select_station4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dest10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Line10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Agency10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        int smds_num = 0;
        int msvs_num = 0;
        Date date1 = null;
        Date date2 = null;
        double difference;
        int difference_s;
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSXXX");
        List<Gtfs_D.Sm_reqT> Siri_sm_req  = new ArrayList<>(); 
        Siri_sm_req.add(new Gtfs_D.Sm_reqT(req_station.getText(),null,60,0,"AC:"));
        ServiceDeliveryStructure Response;
        Clear_labels();
        Status.setText("Send request to MOT server");
        Response = Send_siri_sm_req (Siri_sm_req);
        if (Response.status == false) {
            Status.setText(Response.errorCondition.description.value);
        }
        if (Response.status == true) {
            Status.setText("");
            smds_num = 0;
            for (StopMonitoringDeliveryStructure smds: Response.stopMonitoringDelivery) {
                if (smds.status == false) {
                    Status.setText(smds.errorCondition.description.getValue());
                }                
                if (smds.status == true) {
                    msvs_num = 0;
                    for (MonitoredStopVisitStructure msvs: smds.monitoredStopVisit) {
                        try {
                            date1 = sdf.parse(Response.responseTimestamp.toString());
                            date2 = sdf.parse(msvs.monitoredVehicleJourney.monitoredCall.expectedArrivalTime.toString());
                        } 
                        catch (ParseException ex) {System.out.println("ParseException:"+ex);} 
                        difference = date2.getTime() - date1.getTime();
                        difference_s = (int)difference/60000;
                        
                        if ((msvs_num == 0) && (smds_num == 0)) {
                            Line1.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest1.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency1.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time1.setText(String.valueOf(difference_s));
                        }
                        if ((msvs_num == 1) && (smds_num == 0)) {
                            Line2.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest2.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency2.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time2.setText(String.valueOf(difference_s));
                        }
                        if ((msvs_num == 2) && (smds_num == 0)) {
                            Line3.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest3.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency3.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time3.setText(String.valueOf(difference_s));
                        }

                        if ((msvs_num == 3) && (smds_num == 0)) {
                            Line4.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest4.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency4.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time4.setText(String.valueOf(difference_s));
                        }

                        if ((msvs_num == 4) && (smds_num == 0)) {
                            Line5.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest5.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency5.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time5.setText(String.valueOf(difference_s));
                        }

                        if ((msvs_num == 5) && (smds_num == 0)) {
                            Line6.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest6.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency6.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time6.setText(String.valueOf(difference_s));
                        }

                        if ((msvs_num == 6) && (smds_num == 0)) {
                            Line7.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest7.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency7.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time7.setText(String.valueOf(difference_s));
                        }

                        if ((msvs_num == 7) && (smds_num == 0)) {
                            Line8.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest8.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency8.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time8.setText(String.valueOf(difference_s));
                        }

                        if ((msvs_num == 8) && (smds_num == 0)) {
                            Line9.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest9.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency9.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time9.setText(String.valueOf(difference_s));
                        }

                        if ((msvs_num == 9) && (smds_num == 0)) {
                            Line10.setText (msvs.monitoredVehicleJourney.publishedLineName.getValue());
                            Dest10.setText (msvs.monitoredVehicleJourney.destinationRef.getValue());
                            Agency10.setText(msvs.monitoredVehicleJourney.operatorRef.getValue());
                            Time10.setText(String.valueOf(difference_s));
                        }

                        msvs_num++;
                    }
                }
                msvs_num++;
            }
        }
    }//GEN-LAST:event_doneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siri_sm_demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siri_sm_demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siri_sm_demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siri_sm_demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siri_sm_demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Agency1;
    private javax.swing.JFormattedTextField Agency10;
    private javax.swing.JFormattedTextField Agency2;
    private javax.swing.JFormattedTextField Agency3;
    private javax.swing.JFormattedTextField Agency4;
    private javax.swing.JFormattedTextField Agency5;
    private javax.swing.JFormattedTextField Agency6;
    private javax.swing.JFormattedTextField Agency7;
    private javax.swing.JFormattedTextField Agency8;
    private javax.swing.JFormattedTextField Agency9;
    private javax.swing.JFormattedTextField Dest1;
    private javax.swing.JFormattedTextField Dest10;
    private javax.swing.JFormattedTextField Dest2;
    private javax.swing.JFormattedTextField Dest3;
    private javax.swing.JFormattedTextField Dest4;
    private javax.swing.JFormattedTextField Dest5;
    private javax.swing.JFormattedTextField Dest6;
    private javax.swing.JFormattedTextField Dest7;
    private javax.swing.JFormattedTextField Dest8;
    private javax.swing.JFormattedTextField Dest9;
    private javax.swing.JFormattedTextField Line1;
    private javax.swing.JFormattedTextField Line10;
    private javax.swing.JFormattedTextField Line2;
    private javax.swing.JFormattedTextField Line3;
    private javax.swing.JFormattedTextField Line4;
    private javax.swing.JFormattedTextField Line5;
    private javax.swing.JFormattedTextField Line6;
    private javax.swing.JFormattedTextField Line7;
    private javax.swing.JFormattedTextField Line8;
    private javax.swing.JFormattedTextField Line9;
    private javax.swing.JFormattedTextField Status;
    private javax.swing.JLabel StatusH;
    private javax.swing.JFormattedTextField Time1;
    private javax.swing.JFormattedTextField Time10;
    private javax.swing.JFormattedTextField Time2;
    private javax.swing.JFormattedTextField Time3;
    private javax.swing.JFormattedTextField Time4;
    private javax.swing.JFormattedTextField Time5;
    private javax.swing.JFormattedTextField Time6;
    private javax.swing.JFormattedTextField Time7;
    private javax.swing.JFormattedTextField Time8;
    private javax.swing.JFormattedTextField Time9;
    private javax.swing.JButton done;
    private javax.swing.JTextField req_station;
    private javax.swing.JLabel select_station;
    private javax.swing.JLabel select_station1;
    private javax.swing.JLabel select_station2;
    private javax.swing.JLabel select_station3;
    private javax.swing.JLabel select_station4;
    // End of variables declaration//GEN-END:variables
}
