name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Congrats on taking your first issue friend!'' first issue'
        pr-message: 'Congrats on creating your first pull request friend! Hope it does not suck'' first pr'
